create or replace PACKAGE ADYD_PKG IS

FUNCTION INSERTMODULO(
    V_NOMBRE IN ADYD_MODULOS.TIPO%TYPE
) RETURN NUMBER;

PROCEDURE INSERTFILE(
    V_FILE IN ADYD_FILES.NOMBRE%TYPE,
    V_RUTA IN ADYD_FILES.RUTA%TYPE,
    N_TAMANO IN ADYD_FILES.TAMANHO%TYPE,
    V_TSR_ID1 IN ADYD_TSR.TSR_ID1%TYPE,
    V_TSR_ID2 IN ADYD_TSR.TSR_ID2%TYPE,
    V_RUTA_MINI IN ADYD_MINI.PATH%TYPE,
    N_COLECCION_ID IN ADYD_FILES.COLECCION_ID_FK%TYPE,
    N_CODE OUT NUMBER,
    V_MESSAGE OUT VARCHAR );

FUNCTION GETCOLECCION(
    V_COLECCION IN ADYD_COLECCION.NOMBRE%TYPE
)  RETURN NUMBER;

FUNCTION GETFILE(
    V_FILE IN ADYD_FILES.NOMBRE%TYPE
) RETURN NUMBER;
    
END ADYD_PKG;